# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Email a report
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Email report
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: 'Daily report'
          body: 'Please find attached the daily report'
          to: '